sudo: required
services:
  - docker

before_install:
  - docker build -t yumeind/docker-react -f Dockerfile.dev .

script:
  - docker run yumeind/docker-react npm run test -- --coverage

# deploy:
#   provider: elasticbeanstalk
#   region: "us-west-2" # depends on region where you made elasticbeanstalk
#   app: "docker-react"
#   env: "Docker-env"
#   bucket_name: "elasticbeanstalk-us-west-2-306476627547"
#   bucket_path: "docker-react" # same as app name
#   on:
#     branch: master # deploys when pushed to master branch
#   access_key_id: $AWS_ACCESS_KEY
#   secret_access_key:
#     secure: "$AWS_SECRET_KEY"
